"""add role field in users table

Revision ID: 5261de513546
Revises: fda3a28b39bc
Create Date: 2026-04-17 15:51:31.513052

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5261de513546'
down_revision: Union[str, Sequence[str], None] = 'fda3a28b39bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('role', sa.VARCHAR(), nullable=False, server_default='user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_users', 'role')
    # ### end Alembic commands ###
