"""add review table

Revision ID: 562dd347f94a
Revises: 32828374789a
Create Date: 2026-04-18 18:53:02.518030

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '562dd347f94a'
down_revision: Union[str, Sequence[str], None] = '32828374789a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.Column('book_uid', sa.Uuid(), nullable=False),
    sa.Column('review_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ratting', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['book_uid'], ['books.key'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['auth_users.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('uid')
    )
    op.create_index(op.f('ix_reviews_book_uid'), 'reviews', ['book_uid'], unique=False)
    op.create_index(op.f('ix_reviews_user_uid'), 'reviews', ['user_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_user_uid'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_book_uid'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
