"""update username field to nullabe allow

Revision ID: c336b52bfa40
Revises: d372527ce7dd
Create Date: 2026-04-16 15:10:16.479851

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c336b52bfa40'
down_revision: Union[str, Sequence[str], None] = 'd372527ce7dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_auth_users_username'), table_name='auth_users')
    op.create_index(op.f('ix_auth_users_username'), 'auth_users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_users_username'), table_name='auth_users')
    op.create_index(op.f('ix_auth_users_username'), 'auth_users', ['username'], unique=True)
    op.alter_column('auth_users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
