"""add password field in user model

Revision ID: d372527ce7dd
Revises: 90569e25048b
Create Date: 2026-04-16 15:04:53.585089

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd372527ce7dd'
down_revision: Union[str, Sequence[str], None] = '90569e25048b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_unique_constraint(None, 'auth_users', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_users', type_='unique')
    op.drop_column('auth_users', 'password_hash')
    # ### end Alembic commands ###
